import { Footer } from "@/components/layout/footer";
import { Navigation } from "@/components/layout/navigation";
import { fontMono, fontSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={cn(
          "scroll-smooth bg-background font-sans text-foreground antialiased selection:bg-accent/50",
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
